import yaml from 'yaml'
import type { Entity, Claim, GraphEdge } from '@/lib/studio/types'
import type { OkfBundle, OkfBundleFile } from './types'

export const slug = (s: string): string =>
  s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '') || 'untitled'

/** §4.1: type values are not centrally registered; pick descriptive, self-explanatory strings. */
const OKF_TYPE_MAP: Record<string, string> = {
  note: 'Note',
  concept: 'Concept',
  person: 'Person',
  project: 'Project',
}

/** §3.1: index.md / log.md are reserved and MUST NOT be used for concepts. */
const RESERVED = new Set(['index', 'log'])

function conceptPath(e: Entity): string {
  const typeName = OKF_TYPE_MAP[e.type] ?? 'Concept'
  let name = slug(e.name)
  if (RESERVED.has(name)) name = `${name}-concept` // never collide with reserved filenames
  return `${typeName.toLowerCase()}s/${name}.md`
}

interface SourceEntry {
  id: string
  resource: string
  title?: string
  last_modified?: string
}

function buildConceptDoc(e: Entity, claims: Claim[], studioVersion: string, now: Date): string {
  const frontmatter: Record<string, unknown> = {
    type: OKF_TYPE_MAP[e.type] ?? 'Concept',
    title: e.name,
    description: e.description, // adjust to the actual Entity field used for one-line summaries
    tags: e.tags,
    status: 'stable',
    generated: { by: `do-knowledge-studio/${studioVersion}`, at: now.toISOString() },
  }

  // §5.1 provenance: claims with a source become sources[] entries with STABLE ids
  const sources: SourceEntry[] = []
  const sourceIdByResource = new Map<string, string>()
  for (const c of claims) {
    if (!c.source) continue
    let id = sourceIdByResource.get(c.source)
    if (!id) {
      id = `src-${sources.length + 1}`
      sourceIdByResource.set(c.source, id)
      sources.push({
        id,
        resource: c.source,
        title: c.evidence, // mapping evidence as title or keep resource
        last_modified: c.updatedAt?.slice(0, 10),
      })
    }
  }
  if (sources.length) {
    frontmatter.sources = sources
  }

  const body = [
    e.content ?? '',
    claims.length ? '\n# Claims\n' : '',
    ...claims.map((c) => {
      const id = c.source ? sourceIdByResource.get(c.source) : undefined
      return `- ${c.statement}${id ? `[^${id}]` : ''}`
    }),
    claims.length ? '' : '',
    // §5.1: footnote label is the join key into sources[], NOT positional
    ...sources.map((s) => `[^${s.id}]: ${s.title ?? s.resource}`),
  ]
    .filter((line) => line !== '')
    .join('\n')

  return `---\n${yaml.stringify(frontmatter)}---\n\n${body}\n`
}

function buildIndex(files: OkfBundleFile[], entities: Entity[]): string {
  // §8: root index.md MAY carry okf_version frontmatter (the only index allowed frontmatter)
  const byDir = new Map<string, { title: string; href: string; desc: string }[]>()
  for (const f of files) {
    if (f.path === 'index.md' || f.path === 'log.md') continue
    const parts = f.path.split('/')
    const dir = parts[0]
    const entity = entities.find((e) => f.path.endsWith(`${slug(e.name)}.md`))
    const entries = byDir.get(dir) ?? []
    entries.push({
      title: entity?.name ?? f.path,
      href: `/${f.path}`, // §6.1: bundle-relative absolute links are the recommended form
      desc: entity?.description ?? '',
    })
    byDir.set(dir, entries)
  }
  const sections = [...byDir.entries()]
    .map(([dir, items]) =>
      [
        `# ${dir.charAt(0).toUpperCase() + dir.slice(1)}`,
        '',
        ...items.map((i) => `* [${i.title}](${i.href}) - ${i.desc}`),
      ].join('\n'),
    )
    .join('\n\n')
  return `---\nokf_version: "0.2"\n---\n\n# Knowledge Bundle\n\n${sections}\n`
}

function buildLog(now: Date): string {
  // §9: date headings MUST be ISO YYYY-MM-DD, newest first
  const day = now.toISOString().slice(0, 10)
  return `# Directory Update Log\n\n## ${day}\n* **Export**: Bundle generated by do-knowledge-studio.\n`
}

export function buildOkfBundle(
  entities: Entity[],
  claims: Claim[],
  edges: GraphEdge[],
  studioVersion: string,
  now: Date = new Date(),
): OkfBundle {
  const claimsByEntity = new Map<string, Claim[]>()
  for (const c of claims) {
    claimsByEntity.set(c.entityId, [...(claimsByEntity.get(c.entityId) ?? []), c])
  }

  const conceptFiles: OkfBundleFile[] = entities.map((e) => ({
    path: conceptPath(e),
    content: buildConceptDoc(e, claimsByEntity.get(e.id) ?? [], studioVersion, now),
  }))

  // §6.1: rewrite GraphEdge relationships as bundle-relative markdown links appended
  // under a "# Related" heading in each linked concept (edges are untyped relationships).
  const pathByEntityId = new Map(entities.map((e) => [e.id, `/${conceptPath(e)}`]))
  for (const edge of edges) {
    const from = conceptFiles.find((f) => f.path === pathByEntityId.get(edge.source)?.slice(1))
    const toPath = pathByEntityId.get(edge.target)
    if (from && toPath && !from.content.includes(`](${toPath})`)) {
      from.content = from.content.replace(
        /\n?$/,
        `\n\n# Related\n\n* [${entities.find((e) => e.id === edge.target)?.name ?? toPath}](${toPath})\n`,
      )
    }
  }

  const files: OkfBundleFile[] = [{ path: 'log.md', content: buildLog(now) }, ...conceptFiles]
  files.unshift({ path: 'index.md', content: buildIndex(conceptFiles, entities) })
  return { files, okfVersion: '0.2' }
}
