---
name: Commit Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          fetch-depth: 0

      - name: Lint commit messages
        uses: wagoid/commitlint-github-action@6cf16efdf4da5277c791d335142c03a0bdf1766e  # v6.2.1
        with:
          configFile: commitlint.config.cjs
